[IGTokenProvider] Change error message on invalid offline token fetching [feature/ig4-authentication] (#8824)
### 📝 Description
<!-- A short summary of what this PR does. -->
<!-- Include any relevant context or background information. -->

Change the error message flow when the process of fetching an offline
token fails.
Currently the flow contains the following issues:
- Warnings with retry attempts {0/0}:

> 2025-11-05 14:43:17,801 [warning] Attempt {0/ 0} failed with
exception: 401 Client Error: Unauthorized for url:
https://igz-api.amite.vmdev44ig4.lab.iguazeng.com/api/v1/refresh-access-token
> 2025-11-05 14:43:17,801 [warning] Max retries reached, failed to fetch
token: {"error":"401 Client Error: Unauthorized for url:
https://igz-api.amite.vmdev44ig4.lab.iguazeng.com/api/v1/refresh-access-token"}

This happens because the `max_retries` is initialized during the
IGTokenProvider however the `refresh_token_if_needed` function is called
during it's parent class init - `DynamicTokenProvider`

- Single traceback with the following error message:
> mlrun.errors.MLRunRuntimeError: Failed to fetch access token, no token
available after fetch

The error message is not informative enough, and we have to rely on the
error message displayed in the warning.



The PR fixes the number of retry attempts (3 attempts total) + changes
the displayed error message and chain errors so they are displayed as:

>....
>mlrun.errors.MLRunUnauthorizedError: 401 Client Error: Unauthorized for
url:
https://igz-api.amite.vmdev44ig4.lab.iguazeng.com/api/v1/refresh-access-token
>The above exception was the direct cause of the following exception:
....
>mlrun.errors.MLRunRuntimeError: Failed to fetch a valid access token.
Authentication procedure stopped.



---

### 🛠️ Changes Made
<!-- - Key changes (e.g., added feature X, refactored Y, fixed Z) -->

- Change how we set `DynamicTokenProvider` max_retries value
- Refactor `_refresh_token_if_needed` to display chained error messages

---

### ✅ Checklist
- [ ] I updated the documentation (if applicable)
- [ ] I have tested the changes in this PR
- [ ] I confirmed whether my changes are covered by system tests
- [ ] If yes, I ran all relevant system tests and ensured they passed
before submitting this PR
- [ ] I updated existing system tests and/or added new ones if needed to
cover my changes
- [ ] If I introduced a deprecation:
  - [ ] I followed the [Deprecation Guidelines](./DEPRECATION.md)
  - [ ] I updated the relevant Jira ticket for documentation

---

### 🧪 Testing
<!-- - How it was tested (unit tests, manual, integration) -->  
<!-- - Any special cases covered. -->  


---

### 🔗 References
- Ticket link: https://iguazio.atlassian.net/browse/ML-11266
- Design docs links:
- External links:

---

### 🚨 Breaking Changes?

- [x] Yes (explain below)
- [] No

<!-- If yes, describe what needs to be changed downstream: -->
`OAuthClientIDTokenProvider` which is used in Platform MCK relied on the
error getting raised by `_post_fetch_hook`, which wasn't implemented for
`OAuthClientIDTokenProvider`.
So an invalid token sent in Platform MCK will get errored in the client
side before reaching the API.

---

### 🔍️ Additional Notes
<!-- Anything else reviewers should know (follow-up tasks, known issues,
affected areas etc.). -->
<!-- ### 📸 Screenshots / Logs -->

---------

Co-authored-by: moranbental <107995850+moranbental@users.noreply.github.com>
Co-authored-by: Katerina Molchanova <35141662+rokatyy@users.noreply.github.com>
Co-authored-by: moranbental <moranb@iguazio.com>