[CI] Fix building mlrun image (#8447)
### 📝 Description
Fixed building mlrun image on non-amd64 platform. beforehand the build
were failing on

```
0.078 /bin/sh: 1: /opt/conda/bin/python: not found
------
Dockerfile:54
--------------------
  53 |     
  54 | >>> RUN --mount=type=cache,id=pip-${MLRUN_PYTHON_VERSION},target=/root/.cache/pip \
  55 | >>>     /opt/conda/bin/python -m pip install --upgrade setuptools pip~=${MLRUN_PIP_VERSION}
  56 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c /opt/conda/bin/python -m pip install --upgrade setuptools pip~=${MLRUN_PIP_VERSION}" did not complete successfully: exit code: 127
```

---

### 🛠️ Changes Made
<!-- - Key changes (e.g., added feature X, refactored Y, fixed Z) -->

---

### ✅ Checklist
- [ ] I updated the documentation (if applicable)
- [x] I have tested the changes in this PR

---

### 🧪 Testing
ran `patch_remote.py` to build mlrun / mlrun-kfp and api targets

---

### 🔗 References
- Ticket link:
- Design docs links:
- External links:

---

### 🚨 Breaking Changes?

- [ ] Yes (explain below)
- [x] No


---

### 🔍️ Additional Notes
<!-- Anything else reviewers should know (follow-up tasks, known issues,
affected areas etc.). -->
<!-- ### 📸 Screenshots / Logs -->